import Link from 'next/link'
import './global.css'
import Header from './components/Header'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=''>
        <Header />
       <div className="max-w-7xl min-h-screen pb-28 mx-auto">
       {children}
       </div>
        <footer className="bg-[#f1f1f1] w-full fixed bottom-0 left-0">
          <p className="text-gray-600 max-w-7xl mx-auto text-xs text-center">Copyright &copy; {new Date().getFullYear()} All Rights Reserved</p>
        </footer>
      </body>
    </html>
  )
}
